db_dev:
    image: postgres:10-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: firegallery
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 7432:5432
    volumes:
        - ./DATA:/var/lib/postgresql/data/pgdata
start_dev:
    user: root
    build: ./docker
    command: npm run start:dev
    volumes:
        - ./.firegallery:/root/.firegallery
    ports:
        - 3886:3886
    environment: 
        NODE_ENV: development
        DOCKER_USE: 1
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: firegallery
    links:
        - db_dev