db_test:
    image: postgres:10-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: firegallery-test
    ports:
        - 7432:5432
    volumes:
        - DATA:/var/lib/postgresql/data
test:
    build: ./docker
    command: npm run test
    environment:
        NODE_ENV: test
        DOCKER_USE: 1
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: firegallery
    links:
        - db_test